# This example file from a previous lecture where we ran drupal in docker compose
# in this Assignment, change it to work with the default drupal image, and change
# postgres to use a Swarm secret. More info in the README.md file.

services:

  drupal:
    image: drupal:8.2
    ports:
      - "8080:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles       
      - drupal-sites:/var/www/html/sites      
      - drupal-themes:/var/www/html/themes
    deploy:
      replicas: 3
    
 
  postgres:
    image: postgres:14.3
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
    volumes:
      - drupal-data:/var/lib/postgresql/data
    secrets:
      - db_password


volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:

secrets:
  db_password:
    external: true
      
